language: python
python:
  - "3.8"  

env:
  - DJANGO_SETTINGS_MODULE="assignments.settings"

install:
  - pip install -r assignments/requirements.txt

before_script:
  - black assignments/ --quiet

script:
  - black --check .
  - flake8 .
  - python assignments/manage.py migrate
  - python assignments/manage.py test
  - coverage run assignments/manage.py test  # Run tests with coverage
  - coverage report  # Generate coverage report

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "pollAssignment"
  env: "polls-env"
  bucket_name: "elasticbeanstalk-us-east-1-905418350242"
  on:
    branch: main
